### ISSUE TITLE
Create an action flow diagram

### ISSUE THREAD

**Issue by ryotogashi** [agnosticful/chipstackoverflow-web#14]
- [ ] User sign-up, sign-in and sign-out
- [ ] Listing up recent 5 or 10 posts
- [ ] Seeing posts
- [ ] Creating new posts
- [ ] Editing posts
- [ ] Deleting posts
- [ ] Seeing answers
- [ ] Creating new answers to posts
- [ ] Editing answers
- [ ] Deleting answers
- [ ] Seeing comments
- [ ] Creating new comments to answers
- [ ] Editing comments
- [ ] Deleting comments
- [ ] Putting like or dislike to answers
- [ ] Putting like or dislike to comments
- [ ] Removing like or dislike from answers
- [ ] Removing like or dislike from comments
- [ ] Changing user's name

**Comment by axross** [comment]
Made this https://github.com/agnosticful/chipstackoverflow-web/wiki/User-Actions instead
