### ISSUE TITLE
Brush up User Actions document

### ISSUE THREAD

**Issue by axross** [agnosticful/chipstackoverflow-web#17]
Review and brush up [User Actions](https://github.com/agnosticful/chipstackoverflow-web/wiki/User-Actions) to be MECE

## Requirements

- As the next actions:
    - Can imagine what to do to make rough screen designs (https://github.com/agnosticful/chipstackoverflow-web/issues/18)
    - Can list up what repository-layer code in frontend to write (https://github.com/agnosticful/chipstackoverflow-web/issues/19)
    - Can get started to write backend code (https://github.com/agnosticful/chipstackoverflow-firebase/issues/27)

**Comment by ryotogashi** [comment]
@axross Can you check?

**Comment by axross** [comment]
@ryotogashi Thanks! Mostly done, however,

- "Seeing an answer" section is still quite unclear. Seems there needs to be like and disliked count. Please do **double-check** in comparing others. 
- There's "Signed-in users" top-section. That's strange. Was it creating comments or something like that originally?

**Comment by ryotogashi** [comment]
@axross Thank you for your review!

**Comment by ryotogashi** [comment]
We need to consider how many answers and comments we will show.

**Comment by axross** [comment]
@ryotogashi I think it's okay to show unlimited answers and comments in the first release.

**Comment by ryotogashi** [comment]
@axross okay! thanks

**Comment by ryotogashi** [comment]
@axross Do you think it is proper?
https://github.com/agnosticful/chipstackoverflow-web/wiki/User-Actions#creating-a-new-answer-to-a-post
here, by clicking a cancel button
・Going back to seeing a list of posts

**Comment by ryotogashi** [comment]
https://github.com/agnosticful/chipstackoverflow-web/wiki/User-Actions#creating-a-new-post
same here

**Comment by axross** [comment]
@ryotogashi I think users are supposed to write answers seamlessly on a post detail screen. So they even can just cancel to write an answer.

**Comment by ryotogashi** [comment]
@axross I fixed it.
