### ISSUE TITLE
Make rough screen designs

### ISSUE THREAD

**Issue by axross** [agnosticful/chipstackoverflow-web#18]

**Comment by ryotogashi** [comment]
@axross Can you check?
https://whimsical.com/LkBztS6gVMtDs3heT4BzJt#7YNFXnKbYpGNgBArxsoAk

**Comment by axross** [comment]
@ryotogashi I'll comment here because there's already a lot of comments by yourself, so that you miss out my comments.

In terms of the front page, it would be better if users can imagine what they do in more detail. Here are a few examples what other services do, please check more on yourself and picture how it should be. We cannot proceed to the next step about the front page with the rough sketch as is.

<img width="1440" alt="Screen Shot 2020-03-10 at 12 44 29 PM" src="https://user-images.githubusercontent.com/4289883/76353305-b6a05500-62cd-11ea-9fbb-0a3917b687e8.png">

<img width="1440" alt="Screen Shot 2020-03-10 at 12 42 34 PM" src="https://user-images.githubusercontent.com/4289883/76353111-64f7ca80-62cd-11ea-9520-9b148d66acba.png">

<img width="1440" alt="Screen Shot 2020-03-10 at 12 42 25 PM" src="https://user-images.githubusercontent.com/4289883/76353066-54475480-62cd-11ea-855c-8fd92f8bdcb1.png">

<img width="1440" alt="Screen Shot 2020-03-10 at 12 41 53 PM" src="https://user-images.githubusercontent.com/4289883/76352984-34b02c00-62cd-11ea-9bca-34ea74ae3865.png">

**Comment by axross** [comment]
@ryotogashi I don't think this is completed.

<img width="1043" alt="Screen Shot 2020-03-10 at 12 53 10 PM" src="https://user-images.githubusercontent.com/4289883/76353522-1dbe0980-62ce-11ea-899b-126edbeeedac.png">

**Comment by axross** [comment]
@ryotogashi About this section, I mentioned how the likes and dislikes should look in my opinion, however, I cannot your intention. What I mentioned was UI like YouTube. Did you check it?

<img width="151" alt="Screen Shot 2020-03-10 at 12 56 51 PM" src="https://user-images.githubusercontent.com/4289883/76353804-a0df5f80-62ce-11ea-87f5-3dcc97cfdf5f.png">

<img width="483" alt="Screen Shot 2020-03-10 at 12 53 39 PM" src="https://user-images.githubusercontent.com/4289883/76353651-5362f280-62ce-11ea-9f59-6d677118272b.png">

**Comment by axross** [comment]
@ryotogashi I cannot imagine how it works...

<img width="717" alt="Screen Shot 2020-03-10 at 12 57 28 PM" src="https://user-images.githubusercontent.com/4289883/76353870-b785b680-62ce-11ea-9b0d-288dce3ec5c0.png">

**Comment by axross** [comment]
@ryotogashi I'll send you messages on LINE because there's too much parts needed to point.

**Comment by ryotogashi** [comment]
@axross Can you check?
https://whimsical.com/LkBztS6gVMtDs3heT4BzJt#7YNFXnKbYpGNgBArxsoAk

**Comment by axross** [comment]
@ryotogashi Thanks for you works! I fixed a little bit. By the way, do you have plan for this section?

<img width="411" alt="Screen Shot 2020-03-13 at 9 59 21 AM" src="https://user-images.githubusercontent.com/4289883/76642917-51d53c80-6511-11ea-8900-ef120570ba33.png">

**Comment by ryotogashi** [comment]
@axross I added signed out one and so far let us see how is the situation on a mobile screen.
